apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-hello
  namespace: myargo
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    repoURL: 'https://github.com/sandeep253/node-hello-chart'
    path: '.'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

